#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qalculate-gtk
Version  : 4.4.0
Release  : 6
URL      : https://github.com/Qalculate/qalculate-gtk/releases/download/v4.4.0/qalculate-gtk-4.4.0.tar.gz
Source0  : https://github.com/Qalculate/qalculate-gtk/releases/download/v4.4.0/qalculate-gtk-4.4.0.tar.gz
Summary  : Multi-purpose cross-platform desktop calculator.
Group    : Development/Tools
License  : GPL-2.0
Requires: qalculate-gtk-bin = %{version}-%{release}
Requires: qalculate-gtk-data = %{version}-%{release}
Requires: qalculate-gtk-libexec = %{version}-%{release}
Requires: qalculate-gtk-license = %{version}-%{release}
Requires: qalculate-gtk-locales = %{version}-%{release}
Requires: qalculate-gtk-man = %{version}-%{release}
BuildRequires : gettext
BuildRequires : gmp-dev
BuildRequires : intltool
BuildRequires : mpfr-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libqalculate)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(webkit2gtk-4.0)

%description
Qalculate! GTK UI
Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
to use but provides power and versatility normally reserved for complicated
math packages, as well as useful tools for everyday needs (such as currency
conversion and percent calculation). Features include a large library of
customizable functions, unit calculations and conversion, symbolic calculations
(including integrals and equations), arbitrary precision, uncertainty
propagation, interval arithmetic, plotting, and a user-friendly interface (GTK,
Qt, and CLI).

%package bin
Summary: bin components for the qalculate-gtk package.
Group: Binaries
Requires: qalculate-gtk-data = %{version}-%{release}
Requires: qalculate-gtk-libexec = %{version}-%{release}
Requires: qalculate-gtk-license = %{version}-%{release}

%description bin
bin components for the qalculate-gtk package.


%package data
Summary: data components for the qalculate-gtk package.
Group: Data

%description data
data components for the qalculate-gtk package.


%package doc
Summary: doc components for the qalculate-gtk package.
Group: Documentation
Requires: qalculate-gtk-man = %{version}-%{release}

%description doc
doc components for the qalculate-gtk package.


%package libexec
Summary: libexec components for the qalculate-gtk package.
Group: Default
Requires: qalculate-gtk-license = %{version}-%{release}

%description libexec
libexec components for the qalculate-gtk package.


%package license
Summary: license components for the qalculate-gtk package.
Group: Default

%description license
license components for the qalculate-gtk package.


%package locales
Summary: locales components for the qalculate-gtk package.
Group: Default

%description locales
locales components for the qalculate-gtk package.


%package man
Summary: man components for the qalculate-gtk package.
Group: Default

%description man
man components for the qalculate-gtk package.


%prep
%setup -q -n qalculate-gtk-4.4.0
cd %{_builddir}/qalculate-gtk-4.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667400048
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1667400048
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qalculate-gtk
cp %{_builddir}/qalculate-gtk-%{version}/COPYING %{buildroot}/usr/share/package-licenses/qalculate-gtk/4cc77b90af91e615a64ae04893fdffa7939db84c || :
%make_install
%find_lang qalculate-gtk

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qalculate-gtk

%files data
%defattr(-,root,root,-)
/usr/share/applications/qalculate-gtk.desktop
/usr/share/dbus-1/services/io.github.Qalculate.SearchProvider.service
/usr/share/gnome-shell/search-providers/io.github.Qalculate.search-provider.ini
/usr/share/icons/hicolor/128x128/apps/qalculate.png
/usr/share/icons/hicolor/16x16/apps/qalculate.png
/usr/share/icons/hicolor/22x22/apps/qalculate.png
/usr/share/icons/hicolor/24x24/apps/qalculate.png
/usr/share/icons/hicolor/256x256/apps/qalculate.png
/usr/share/icons/hicolor/32x32/apps/qalculate.png
/usr/share/icons/hicolor/48x48/apps/qalculate.png
/usr/share/icons/hicolor/64x64/apps/qalculate.png
/usr/share/icons/hicolor/scalable/apps/qalculate.svg
/usr/share/metainfo/qalculate-gtk.appdata.xml

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/qalculate\-gtk/*

%files libexec
%defattr(-,root,root,-)
/usr/libexec/qalculate-search-provider

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qalculate-gtk/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/qalculate-gtk.1

%files locales -f qalculate-gtk.lang
%defattr(-,root,root,-)

