#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: 750e50d
#
Name     : qalculate-gtk
Version  : 4.5.0
Release  : 13
URL      : https://github.com/Qalculate/qalculate-gtk/releases/download/v4.5.0/qalculate-gtk-4.5.0.tar.gz
Source0  : https://github.com/Qalculate/qalculate-gtk/releases/download/v4.5.0/qalculate-gtk-4.5.0.tar.gz
Summary  : Multi-purpose cross-platform desktop calculator.
Group    : Development/Tools
License  : GPL-2.0
Requires: qalculate-gtk-bin = %{version}-%{release}
Requires: qalculate-gtk-data = %{version}-%{release}
Requires: qalculate-gtk-libexec = %{version}-%{release}
Requires: qalculate-gtk-license = %{version}-%{release}
Requires: qalculate-gtk-locales = %{version}-%{release}
Requires: qalculate-gtk-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gettext
BuildRequires : gmp-dev
BuildRequires : intltool
BuildRequires : mpfr-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libqalculate)
BuildRequires : pkgconfig(libxml-2.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Qalculate! GTK UI
Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
to use but provides power and versatility normally reserved for complicated
math packages, as well as useful tools for everyday needs (such as currency
conversion and percent calculation). Features include a large library of
customizable functions, unit calculations and conversion, symbolic calculations
(including integrals and equations), arbitrary precision, uncertainty
propagation, interval arithmetic, plotting, and a user-friendly interface (GTK,
Qt, and CLI).

%package bin
Summary: bin components for the qalculate-gtk package.
Group: Binaries
Requires: qalculate-gtk-data = %{version}-%{release}
Requires: qalculate-gtk-libexec = %{version}-%{release}
Requires: qalculate-gtk-license = %{version}-%{release}

%description bin
bin components for the qalculate-gtk package.


%package data
Summary: data components for the qalculate-gtk package.
Group: Data

%description data
data components for the qalculate-gtk package.


%package doc
Summary: doc components for the qalculate-gtk package.
Group: Documentation
Requires: qalculate-gtk-man = %{version}-%{release}

%description doc
doc components for the qalculate-gtk package.


%package libexec
Summary: libexec components for the qalculate-gtk package.
Group: Default
Requires: qalculate-gtk-license = %{version}-%{release}

%description libexec
libexec components for the qalculate-gtk package.


%package license
Summary: license components for the qalculate-gtk package.
Group: Default

%description license
license components for the qalculate-gtk package.


%package locales
Summary: locales components for the qalculate-gtk package.
Group: Default

%description locales
locales components for the qalculate-gtk package.


%package man
Summary: man components for the qalculate-gtk package.
Group: Default

%description man
man components for the qalculate-gtk package.


%prep
%setup -q -n qalculate-gtk-4.5.0
cd %{_builddir}/qalculate-gtk-4.5.0
pushd ..
cp -a qalculate-gtk-4.5.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707099859
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707099859
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qalculate-gtk
cp %{_builddir}/qalculate-gtk-%{version}/COPYING %{buildroot}/usr/share/package-licenses/qalculate-gtk/4cc77b90af91e615a64ae04893fdffa7939db84c || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
%find_lang qalculate-gtk
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/qalculate-gtk
/usr/bin/qalculate-gtk

%files data
%defattr(-,root,root,-)
/usr/share/applications/qalculate-gtk.desktop
/usr/share/dbus-1/services/io.github.Qalculate.SearchProvider.service
/usr/share/gnome-shell/search-providers/io.github.Qalculate.search-provider.ini
/usr/share/icons/hicolor/128x128/apps/qalculate.png
/usr/share/icons/hicolor/16x16/apps/qalculate.png
/usr/share/icons/hicolor/22x22/apps/qalculate.png
/usr/share/icons/hicolor/24x24/apps/qalculate.png
/usr/share/icons/hicolor/256x256/apps/qalculate.png
/usr/share/icons/hicolor/32x32/apps/qalculate.png
/usr/share/icons/hicolor/48x48/apps/qalculate.png
/usr/share/icons/hicolor/64x64/apps/qalculate.png
/usr/share/icons/hicolor/scalable/apps/qalculate.svg
/usr/share/metainfo/qalculate-gtk.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/qalculate\-gtk/*

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/qalculate-search-provider
/usr/libexec/qalculate-search-provider

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qalculate-gtk/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/qalculate-gtk.1

%files locales -f qalculate-gtk.lang
%defattr(-,root,root,-)

